### ISSUE TITLE
Is there a list of libre book like yours?

### ISSUE THREAD

**Issue by aloisdg** [Deevad/peppercarrot#5]
Hello,

I just bought your BD (ty glénat!) and I would love to get more libre books. Is there a list somewhere?

Thank you and keep going!

**Comment by Deevad** [comment]
Hey @aloisdg ,
Thank you! 
I don't know if there is an official list of free/libre comic book ( or books ). Certainly not a long list :)
What are you looking for? Something specific? or just a listing?

**Comment by valvin1** [comment]
Maybe you should have a look here : http://framabook.org but P&C is not (yet) there :)

**Comment by aloisdg** [comment]
@Deevad A simple list would be good enough.

**Comment by craigmaloney** [comment]
Hi @aloisdg,

Are you looking for print books or digital books? Just comic books? 

I'm not aware of one canonical list or grouping (There's several disparate collections and lists out there). Perhaps that's something that can be compiled

**Comment by aloisdg** [comment]
@craigmaloney Print books. Mostly for gifts.

**Comment by craigmaloney** [comment]
@aloisdg I'm sure they'll all love a copy of Larry Lessig's "Free Culture" then. :) http://www.free-culture.cc/

All kidding aside this gets into some tricky territory. I know of several print RPGs that are CC-BY, but the print versions don't say that anywhere in the book (Fate, Dungeon World). Eclipse Phase says it in the first few pages but it's CC-BY-NC-SA. Cory Doctorow publishes his books online but IIRC he doesn't mention the license in the print books.

Which gets back to the original question: there isn't a curated list that we're aware of of all of the libre books out there. At best there's collections (Project Gutenberg for starters) and a smattering of authors and publishers that think free culture is pretty neat. I know there's an effort underway for Creative Commons to list these works (they're currently working on getting image data from places like Flickr that DO have searchable licenses), but having a list of all of the CC books (in print or otherwise) is a daunting task.

That said if you want some help with finding some books and can give out some of the topics and interests I'll do my best to hook them up with a CC-licensed work.

**Comment by aloisdg** [comment]
@craigmaloney I hope to play Dungeon World one day!

Aside, I can just create a repository-based list a let people submit contents. Something like awesome-libre-books (also awesome-libre-cd/dvd whatever could be nice). A kind of showcase of libre project dealing with the industry and how to start a free world.

**Comment by craigmaloney** [comment]
@aloisdg Woo hoo (re: Dungeon World)

I asked in the #creativecommons channel (on Freenode) and they pointed me to a few resources that might be of interest:

https://www.worldcat.org/search?q=kw%3A%22creative+commons%22&fq=fm%3Afic&dblist=638&start=1&qt=page_number_link

Searching on "Creative Commons" and then picking the "Fiction" category lead to these books (some of which I did not know were CC-licensed).

https://en.wikipedia.org/wiki/List_of_major_Creative_Commons_licensed_works

This lists our beloved P&C, but also has stuff that I wasn't aware was CC-licensed (like "Warbreaker" by Brandon Sanderson).

**Comment by aloisdg** [comment]
@craigmaloney [8 entries](https://en.wikipedia.org/wiki/List_of_major_Creative_Commons_licensed_works#Comics) Damn it is a bit sad. Glad to see a list already exists! Also it has to start somewhere. I hope it will grow.

**Comment by craigmaloney** [comment]
@aloisdg Me too. There's a few things I know that are missing from that list (Talislanta for one). 

Here's hoping someday that such a list won't be necessary. :)

TTYL!
